
server:
  port: 5000
  tomcat:
    connection-timeout:
      30

spring:
  application:
    name: testquerydsl
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: postgres
    password: postgres
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
